### ISSUE TITLE
speaker_embedding_dimension

### ISSUE THREAD

**Issue by tshmak** [deterministic-algorithms-lab/Cross-Lingual-Voice-Cloning#9]
Line [220](https://github.com/deterministic-algorithms-lab/Cross-Lingual-Voice-Cloning/blob/c922ce25e20de0a247c211d621ab04aeac81cc9d/model.py#L220) in [model.py](https://github.com/deterministic-algorithms-lab/Cross-Lingual-Voice-Cloning/blob/master/model.py): 
```
self.speaker_embedding_dim = hparams.encoder_embedding_dim
```
Should be 
```
self.speaker_embedding_dim = hparams.speaker_embedding_dim
```
??

**Comment by Jeevesh8** [comment]
Yes, you're right @tshmak . I probably did that because I wanted to add/point-wise multiply the speaker embeddings to the the encoder output, rather than concatenate them. 

But it shouldn't lead to a problem, as I don't think that attribute(``self.speaker_embedding_dim``) is being used elsewhere.

Do you want to open a pull request? Or shall I correct ?

**Comment by tshmak** [comment]
Please correct, as my repository contains other modifications to your program also. Just to clarify, your program concats rather than add/multiply the speaker embedding right? (cf. [here](https://github.com/deterministic-algorithms-lab/Cross-Lingual-Voice-Cloning/blob/c922ce25e20de0a247c211d621ab04aeac81cc9d/model.py#L412)). Is it because you tried add/multiply and in the end decided to stick with concat?

**Comment by Jeevesh8** [comment]
@tshmak Yes, the program concats right now. It is because the papers says to concatenate. Although, I am yet to try multiplying/adding , but i lost server access, so couldn't do.
